[ids]
*

[main]
rightalt=leftalt
leftalt=overload(alt, leftmeta)
rightshift=overload(shift, rightshift)

[alt]
# @: normal wiondows key
# q=macro(rightalt+q)
# @: this is the native in macos i believe
# l=macro(rightalt+q) 
# @: current setting
[=macro(rightalt+q)
# €
e=macro(rightalt+e)
# brackets
7=macro(rightalt+7)
8=macro(rightalt+8)
9=macro(rightalt+9)
0=macro(rightalt+0)
# \¸
==macro(rightalt+=)
-=macro(rightalt+-)
# ~
]=macro(rightalt+])
# |
102nd=macro(rightalt+102nd)
# *mac-like* (optional)
# - z is recongized as y ... :D
a=macro(leftcontrol+a)
l=macro(leftcontrol+l)
v=macro(leftcontrol+v)
w=macro(leftcontrol+w)
x=macro(leftcontrol+x)
c=macro(leftcontrol+c)
y=macro(leftcontrol+y)
q=macro(leftcontrol+q)
backspace=macro(leftcontrol+backspace)

[shift]
# *nautilus-hack*
backspace=macro(leftalt+up)