[ids]
*

[main]

#
# Right Shift activates a special "nav" layer when held
#
rightshift = layer(nav)

#
# Left Alt:
#  - tap   → Left Alt
#  - hold  → activates brackets layer AND holds Alt
#
leftalt = overload(brackets, leftalt)

[brackets:leftalt]
` = macro(leftalt+`)
1 = macro(leftalt+1)
7 = macro(rightalt+7)
8 = macro(rightalt+8)
9 = macro(rightalt+9)
0 = macro(rightalt+0)
left = macro(leftalt+left)
right = macro(leftalt+right)
up = macro(leftalt+up)
down = macro(leftalt+down)
space = macro(leftalt+space)
#tab = overload(brackets, tab)
#tab = macro(leftalt+tab)

#[brackets]
#tab = M-tab

))))


[nav:shift]
#
# nautlius fix: holding Rightshift + Backspace
# maps to leftalt + up (going up in nautlius defautl settings)
#
backspace = macro(leftalt+up)

#
# I must also add all other combinations
#
a = macro(leftshift+a)
b = macro(leftshift+b)
c = macro(leftshift+c)
d = macro(leftshift+d)
e = macro(leftshift+e)
f = macro(leftshift+f)
g = macro(leftshift+g)
h = macro(leftshift+h)
i = macro(leftshift+i)
j = macro(leftshift+j)
k = macro(leftshift+k)
l = macro(leftshift+l)
m = macro(leftshift+m)
n = macro(leftshift+n)
o = macro(leftshift+o)
p = macro(leftshift+p)
q = macro(leftshift+q)
r = macro(leftshift+r)
s = macro(leftshift+s)
t = macro(leftshift+t)
u = macro(leftshift+u)
v = macro(leftshift+v)
w = macro(leftshift+w)
x = macro(leftshift+x)
y = macro(leftshift+y)
z = macro(leftshift+z)

1 = macro(leftshift+1)
2 = macro(leftshift+2)
3 = macro(leftshift+3)
4 = macro(leftshift+4)
5 = macro(leftshift+5)
6 = macro(leftshift+6)
7 = macro(leftshift+7)
8 = macro(leftshift+8)
9 = macro(leftshift+9)
0 = macro(leftshift+0)

] = macro(leftshift+])
102nd = macro(leftshift+102nd)
leftbracket = macro(leftshift+leftbracket)
rightbracket = macro(leftshift+rightbracket)
backslash = macro(leftshift+backslash)
semicolon = macro(leftshift+semicolon)
quote = macro(leftshift+quote)
comma = macro(leftshift+comma)
dot = macro(leftshift+dot)
minus = macro(leftshift+minus)
equal = macro(leftshift+equal)
tab = macro(leftshift+tab)
slash = macro(leftshift+slash)
