# [ids]
# *

# [main]
# leftalt = overload(brackets, leftalt)
# rightalt = layer(nav)

# [brackets:rightalt]
# 7 = macro(rightalt+7)   # {
# 8 = macro(rightalt+8)   # [
# 9 = macro(rightalt+9)   # ]
# 0 = macro(rightalt+0)   # }

# [brackets:leftalt]

# # defaults
# ` = macro(leftalt+`)
# tab = macro(leftalt+tab)
# 1 = macro(leftalt+1)
# 2 = macro(leftalt+2)
# 3 = macro(leftalt+3)
# 4 = macro(leftalt+4)
# 5 = macro(leftalt+5)
# 6 = macro(leftalt+6)
# up = macro(leftalt+up)
# left = macro(leftalt+left)
# down = macro(leftalt+down)
# space = macro(leftalt+space)
# right = macro(leftalt+right)

# # altered
# 7 = macro(rightalt+7)   # {
# 8 = macro(rightalt+8)   # [
# 9 = macro(rightalt+9)   # ]
# 0 = macro(rightalt+0)   # }
# q = macro(rightalt+q)   # @
# e = macro(rightalt+e)   # €
# ] = macro(rightalt+])   # ~
# - = macro(rightalt+-)   # ¸ (´`)
# = = macro(rightalt+=)   # \ (?, ß)

# #
# # *nautlius fix*
# # Holding RightAlt + Backspace to map to leftalt + up
# # (going previous selection; default settings in nautilus)
# #
# [nav:rightalt]
# backspace = macro(leftalt+up)

[ids]
*

[main]
rightalt = layer(nav)

#
# *nautlius fix*
# Holding RightAlt + Backspace to map to leftalt + up
# (going previous selection; default settings in nautilus)
#
[nav:rightalt]
backspace = macro(leftalt+up)


# leftalt = layer(test)


# [test:A]
# backspace = A-up


# [ids]
# *

# [main]

# leftalt = overload(brackets, leftalt)
# # rightalt = overload(brackets, leftalt)
# # backspace = macro(leftalt+up)

# [test:leftalt]
# backspace=macro(leftalt+up)

# [brackets:leftalt]

# # default
# ` = macro(leftalt+`)

# # default
# tab = macro(leftalt+tab)

# # default
# 1 = macro(leftalt+1)

# # default
# 2 = macro(leftalt+2)

# # default
# 3 = macro(leftalt+3)

# # default
# 4 = macro(leftalt+4)

# # default
# 5 = macro(leftalt+5)

# # default
# 6 = macro(leftalt+6)

# # default
# up = macro(leftalt+up)

# # default
# left = macro(leftalt+left)

# # default
# down = macro(leftalt+down)

# # default
# space = macro(leftalt+space)

# # default
# right = macro(leftalt+right)

# # {
# 7 = macro(rightalt+7)

# # [
# 8 = macro(rightalt+8)

# # ]
# 9 = macro(rightalt+9)

# # }
# 0 = macro(rightalt+0)

# # @
# q = macro(rightalt+q)

# # €
# e = macro(rightalt+e)

# # ~
# ] = macro(rightalt+])

# # ¸ (´`)
# - = macro(rightalt+-)

# # \ (?, ß)
# = = macro(rightalt+=)

# # DEPRECATED
# # asinging the switch desktop just for rightalt (parallel)
# # - = macro(leftalt+`)
# # = = macro(leftalt+1)
