[ids]
*

[main]
rightalt = layer(rightalt_layered)
leftalt = layer(leftalt_layered)


#
# RIGHTALT
#
[rightalt_layered]

# *nautilus hack*
backspace=macro(leftalt+up)

# *search light*
space = macro(leftalt+space)

# *mac-like*
c = macro(leftcontrol+c)
a = macro(leftcontrol+a)
v = macro(leftcontrol+v)
q = macro(leftcontrol+q)
w = macro(leftcontrol+w)
l = macro(leftcontrol+l)

# *just defaults*
7 = macro(rightalt+7)
8 = macro(rightalt+8)
9 = macro(rightalt+9)
0 = macro(rightalt+0)
q = macro(rightalt+q)
e = macro(rightalt+e)
` = macro(rightalt+`)
1 = macro(rightalt+1)
2 = macro(rightalt+2)
3 = macro(rightalt+3)
4 = macro(rightalt+4)
5 = macro(rightalt+5)
6 = macro(rightalt+6)
7 = macro(rightalt+7)
8 = macro(rightalt+8)
9 = macro(rightalt+9)
0 = macro(rightalt+0)
q = macro(rightalt+q)
e = macro(rightalt+e)
] = macro(rightalt+])
- = macro(rightalt+-)
= = macro(rightalt+=)
tab = macro(leftalt+tab)
up = macro(rightalt+up)
left = macro(rightalt+left)
down = macro(rightalt+down)
right = macro(rightalt+right)


#
# LEFTALT
#
[leftalt_layered]

# *nautilus hack*
backspace=macro(leftalt+up)

# *search light*
space = macro(leftalt+space)

# *switch virtual desktops*
` = macro(leftalt+`)
1 = macro(leftalt+1)

# *mac-like*
c = macro(leftcontrol+c)
a = macro(leftcontrol+a)
v = macro(leftcontrol+v)
q = macro(leftcontrol+q)
w = macro(leftcontrol+w)
l = macro(leftcontrol+l)

# *just defaults*
7 = macro(rightalt+7)
8 = macro(rightalt+8)
9 = macro(rightalt+9)
0 = macro(rightalt+0)
q = macro(rightalt+q)
e = macro(rightalt+e)
2 = macro(rightalt+2)
3 = macro(rightalt+3)
4 = macro(rightalt+4)
5 = macro(rightalt+5)
6 = macro(rightalt+6)
7 = macro(rightalt+7)
8 = macro(rightalt+8)
9 = macro(rightalt+9)
0 = macro(rightalt+0)
q = macro(rightalt+q)
e = macro(rightalt+e)
] = macro(rightalt+])
- = macro(rightalt+-)
= = macro(rightalt+=)
tab = macro(leftalt+tab)
up = macro(rightalt+up)
left = macro(rightalt+left)
down = macro(rightalt+down)
right = macro(rightalt+right)
